GET http://localhost:3000/api/v0/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTRkNGIyY2Q0YzgwNDJhOGFjMTdiYiIsIm5hbWUiOiJkZW55bHNvbiIsImlhdCI6MTc3MTM2MTUxMiwiZXhwIjoxNzcxMzYyNDEyfQ.wnRTIA2bQUPym6eYEDRUV5LY1aKbywJnFJDAzAzhf4E