GET http://localhost:3000/api/v0/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWE1YzU2OGM5NmQ2ZWQxYzc3OTc4MCIsIm5hbWUiOiJkZW55eiIsImlhdCI6MTc3MTcyNTkyNywiZXhwIjoxNzcxNzI2ODI3fQ.FNa_I8gCVtjrI26CEoJXA5KHmv2MOl8lEYu2ymI6NmM